hosted_match_locations:
  - Sollentuna Rackethall
  - Kista Rackethall
  - Komethallen
  - Enskede Rackethall
  - Frescati Racketcenter
  - Sundbyberg Rackethall
  - Skogas Rackethall
  - BadmintonStadion Skanstul
  - Other
